# Generated by Django 6.0.4 on 2026-05-04 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre descriptivo de la actividad.', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Detalles y objetivos de la actividad.', verbose_name='Descripción')),
                ('fecha', models.DateField(help_text='Día en que se realizará la actividad.', verbose_name='Fecha')),
                ('hora', models.TimeField(help_text='Horario de inicio de la actividad.', verbose_name='Hora')),
                ('lugar', models.CharField(help_text='Ubicación dentro del CEA donde se realizará.', max_length=200, verbose_name='Lugar')),
                ('cupo_maximo', models.PositiveIntegerField(help_text='Número máximo de voluntarios que pueden participar.', verbose_name='Cupo máximo')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', help_text='Etapa actual de la actividad.', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('responsable', models.ForeignKey(help_text='Usuario admin encargado de la actividad.', on_delete=django.db.models.deletion.PROTECT, related_name='actividades_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se registró la inscripción.', verbose_name='Fecha de inscripción')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('EN_ESPERA', 'En espera'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', help_text='Situación actual de la inscripción.', max_length=20, verbose_name='Estado')),
                ('actividad', models.ForeignKey(help_text='Actividad a la que se inscribe el voluntario.', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='activities.actividad', verbose_name='Actividad')),
                ('voluntario', models.ForeignKey(help_text='Usuario voluntario que se inscribe.', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL, verbose_name='Voluntario')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('actividad', 'voluntario')},
            },
        ),
    ]
