# Generated by Django 6.0.4 on 2026-05-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='asistio',
            field=models.BooleanField(default=False, help_text='Indica si el voluntario asistió a la actividad.', verbose_name='Asistió'),
        ),
    ]
