# Generated by Django 5.2.8 on 2026-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_inscripcion_asistio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
