# Generated by Django 5.2.8 on 2026-05-04 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(help_text='Nombre con el que se conoce popularmente la especie.', max_length=100, verbose_name='Nombre común')),
                ('nombre_cientifico', models.CharField(blank=True, help_text='Nombre científico de la especie (opcional).', max_length=150, verbose_name='Nombre científico')),
                ('descripcion', models.TextField(help_text='Descripción general de la especie.', verbose_name='Descripción')),
                ('condiciones_cultivo', models.TextField(help_text='Detalles de suelo, luz, temperatura y otros requisitos.', verbose_name='Condiciones de cultivo')),
                ('frecuencia_riego', models.CharField(help_text='Cada cuánto tiempo se debe regar (ej: "Cada 2 días", "3 veces por semana").', max_length=100, verbose_name='Frecuencia de riego')),
                ('temporada_recomendada', models.CharField(choices=[('PRIMAVERA_VERANO', 'Primavera-Verano'), ('OTONIO_INVIERNO', 'Otoño-Invierno'), ('ANUAL', 'Anual')], help_text='Época del año más adecuada para su cultivo.', max_length=30, verbose_name='Temporada recomendada')),
                ('imagen', models.ImageField(blank=True, help_text='Fotografía de referencia de la especie.', upload_to='especies/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['nombre_comun'],
            },
        ),
        migrations.CreateModel(
            name='CicloCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField(help_text='Día en que se sembró la especie.', verbose_name='Fecha de siembra')),
                ('fecha_cosecha_estimada', models.DateField(help_text='Fecha calculada o estimada para la cosecha.', verbose_name='Fecha estimada de cosecha')),
                ('estado', models.CharField(choices=[('SEMBRADO', 'Sembrado'), ('EN_CRECIMIENTO', 'En crecimiento'), ('LISTO_COSECHA', 'Listo para cosecha'), ('COSECHADO', 'Cosechado')], default='SEMBRADO', help_text='Etapa actual del ciclo de cultivo.', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, help_text='Notas y resultado final del ciclo (opcional).', verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('especie', models.ForeignKey(help_text='Especie cultivada en este ciclo.', on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='crops.especie', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Ciclo de cultivo',
                'verbose_name_plural': 'Ciclos de cultivo',
                'ordering': ['-fecha_siembra'],
            },
        ),
    ]
